# Generated by Django 4.1.7 on 2023-04-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_alter_task_options_rename_datetime_task_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tag',
        ),
        migrations.AddField(
            model_name='task',
            name='tag',
            field=models.ManyToManyField(related_name='tasks', to='list.tag'),
        ),
    ]
